version: '3.8'

services:
  db:
    image: 'postgres:16.4'
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=dev_user
      - POSTGRES_PASSWORD=dev_password
      - POSTGRES_DB=dev_database
