INSERT INTO anime (title, description, episodes)
VALUES ('Naruto', 'A young ninja who seeks recognition and dreams of becoming the Hokage.', 220),
       ('One Piece', 'A pirate adventure to find the One Piece and become the Pirate King.', 1000),
       ('Attack on Titan',
        'Eren Yeager fights to free his people from the Titans, giant humanoids that have destroyed most of humanity.',
        87),
       ('Dragon Ball Z',
        'Goku, a powerful warrior, defends Earth from villains and seeks stronger opponents through various epic battles.',
        291),
       ('Fullmetal Alchemist: Brotherhood',
        'Brothers Edward and Alphonse Elric search for the Philosopher''s Stone after a failed alchemy experiment.',
        64),
       ('Death Note',
        'Light Yagami finds a notebook that grants him the power to kill anyone whose name he writes in it, and embarks on a mission of justice.',
        37),
       ('My Hero Academia',
        'Izuku Midoriya, a quirkless boy in a world of superheroes, dreams of becoming a hero and attends U.A. High School.',
        113),
       ('Demon Slayer',
        'Tanjiro Kamado joins the Demon Slayer Corps to avenge his family and cure his sister Nezuko, who has turned into a demon.',
        44),
       ('Sword Art Online',
        'Kirito, a skilled gamer, finds himself trapped in a virtual reality MMORPG where dying in the game means dying in real life.',
        96),
       ('Hunter x Hunter',
        'Gon Freecss becomes a Hunter to find his father and embarks on an epic journey of friendship, battles, and discoveries.',
        148),
       ('Tokyo Ghoul',
        'Ken Kaneki, a college student, becomes a half-ghoul after a deadly encounter and struggles to survive in a world full of ghouls.',
        48),
       ('Bleach',
        'Ichigo Kurosaki gains the powers of a Soul Reaper and must protect humans from evil spirits while guiding the souls of the deceased.',
        366),
       ('Fairy Tail',
        'Natsu Dragneel, a dragon slayer wizard, embarks on adventures with the Fairy Tail guild in a world full of magic and mystery.',
        328),
       ('Steins;Gate',
        'Rintarou Okabe, a self-proclaimed mad scientist, stumbles upon a way to send messages to the past and faces the consequences.',
        24),
       ('Cowboy Bebop',
        'Spike Spiegel and his ragtag crew of bounty hunters travel across the galaxy in search of lucrative bounties.',
        26),
       ('Neon Genesis Evangelion',
        'Shinji Ikari pilots a giant bio-machine to protect humanity from mysterious creatures called Angels.', 26),
       ('Black Clover',
        'Asta, a boy born without magic, dreams of becoming the Wizard King and faces off against powerful enemies with his anti-magic sword.',
        170),
       ('Re:Zero - Starting Life in Another World',
        'Subaru Natsuki is transported to a fantasy world where he finds himself with the ability to "reset" after dying.',
        50),
       ('Mob Psycho 100',
        'Shigeo Kageyama, also known as Mob, is a powerful esper who tries to live a normal life while dealing with his psychic abilities.',
        25),
       ('The Seven Deadly Sins',
        'The Seven Deadly Sins, once the strongest knights in the kingdom, must now protect the land from a new threat.',
        100);
